END_CERTIFICATE_DURATION_IN_DAYS: 180
INTERMEDIATE_CERTIFICATE_DURATION_IN_DAYS: 365
ROOT_CERTIFICATE_DURATION_IN_DAYS: 3650
CERTIFICATE_VERSION: "v3"
SIGNATURE_ALGORITHM: "SHA256WithRSAEncryption"
EMAIL_FROM: "aleksandar.petrovic.web@gmail.com"
VERIFICATION_EXPIRATION_IN_MS: 3600000
TWILIO_SID: "AC596b54da12cf4904946d4909799d11d9"
TWILIO_TOKEN: "1afeb618bd24cd2de406b664885d2290"
TWILIO_PHONE: "+16076227613"